//! A pure-Rust reimplementation of the subset of RakNet's `BitStream` the game uses.
//!
//! Verified byte-for-byte against the real `libRakNet.so` — see `tests/bitstream_golden.rs`
//! and the vectors it reads, which were generated by `tools/bitstream-golden`. Nothing here
//! is inferred from reading the RakNet source; every rule below is a captured measurement.
//!
//! # The three rules
//!
//! 1. **Bits fill each byte from the most significant end down.** The first bit written
//!    lands in `0x80`, not `0x01`.
//!
//! 2. **`write_uint` walks the value's little-endian bytes**, each contributing eight bits
//!    most-significant-first. This is the C#'s `WriteBits(BitConverter.GetBytes(v), n, true)`
//!    idiom. Two consequences that look wrong but are not:
//!
//!    - A full 32-bit write comes out **byte-reversed**: `0x12345678` → `78 56 34 12`.
//!    - A width that is not a multiple of eight is *not* "the low `n` bits of the value".
//!      15 bits of `12800` is byte 0 (`0x00`) followed by the low 7 bits of byte 1 (`0x32`),
//!      giving `00 64` — it does **not** encode 12800 in any recoverable way. Widths under 8
//!      behave as you would expect; wider odd widths only make sense for values that fit in
//!      the whole bytes involved.
//!
//! 3. **The final partial byte contributes its low bits**, emitted most-significant-first.
//!
//! Rule 2's second point is a real trap. `SkySaga.Game`'s `TryReadBitsValue` documents the
//! read-side half of it, and the 15-bit pitch fields in `EntityMoved` / `SetLookAtDirection`
//! are decoded wrongly in the C# because of it.

use thiserror::Error;

/// RakNet's first user-assignable message id. Game packet ids are offsets from here.
pub const ID_USER_PACKET_ENUM: u16 = 134;

/// A string field's length is a single byte unless the `largeLength` bit is set.
const MAX_SHORT_STRING: usize = 255;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum BitError {
    #[error("read past the end: wanted {wanted} bits, {available} remain")]
    OutOfBounds { wanted: usize, available: usize },

    #[error("string field is not valid UTF-8")]
    BadUtf8,

    #[error("large-length strings are not implemented (the game never sends one)")]
    LargeStringLength,
}

// --- writing --------------------------------------------------------------------------------

/// Appends bits most-significant-first, exactly as RakNet does.
#[derive(Debug, Default, Clone)]
pub struct BitWriter {
    data: Vec<u8>,
    bits: usize,
}

impl BitWriter {
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of bits written so far. RakNet sends this, not the byte count.
    pub fn bits_used(&self) -> usize {
        self.bits
    }

    /// The packet, padded to a whole number of bytes.
    pub fn as_bytes(&self) -> &[u8] {
        &self.data
    }

    pub fn into_bytes(self) -> Vec<u8> {
        self.data
    }

    pub fn is_empty(&self) -> bool {
        self.bits == 0
    }

    pub fn write_bit(&mut self, bit: bool) {
        let offset = self.bits % 8;

        if offset == 0 {
            self.data.push(0);
        }

        if bit {
            let last = self.data.len() - 1;

            self.data[last] |= 0x80 >> offset;
        }

        self.bits += 1;
    }

    pub fn write_u8(&mut self, value: u8) {
        self.write_byte_bits(value, 8);
    }

    /// Write the top `count` bits of `value` (`count <= 8`), most-significant-first.
    fn write_byte_bits(&mut self, value: u8, count: u32) {
        for index in 0..count {
            self.write_bit(value & (0x80 >> index) != 0);
        }
    }

    /// Write `bits` bits of `value`, following rule 2 in the module docs.
    ///
    /// Mirrors `WriteBits(BitConverter.GetBytes(value), bits, rightAligned: true)`.
    pub fn write_uint(&mut self, value: u32, bits: u32) {
        self.write_bits(&value.to_le_bytes(), bits);
    }

    /// The general form: consume `bits` bits from `bytes`, in order.
    ///
    /// Each whole byte contributes all eight of its bits, most-significant-first. A trailing
    /// partial byte contributes its **low** bits, also most-significant-first — RakNet does
    /// this by left-shifting the byte first, which is where "right aligned" comes from.
    pub fn write_bits(&mut self, bytes: &[u8], bits: u32) {
        let mut remaining = bits;
        let mut index = 0;

        while remaining > 0 {
            let byte = bytes.get(index).copied().unwrap_or(0);

            if remaining >= 8 {
                self.write_byte_bits(byte, 8);
                remaining -= 8;
            } else {
                self.write_byte_bits(byte << (8 - remaining), remaining);
                remaining = 0;
            }

            index += 1;
        }
    }

    /// `hasData` bit, `largeLength` bit, an 8-bit length, then the UTF-8 bytes.
    ///
    /// An empty string is a single `0` bit — the client reads that back as empty, so the
    /// length and body are not written at all.
    pub fn write_string(&mut self, value: &str) {
        if value.is_empty() {
            self.write_bit(false);

            return;
        }

        self.write_bit(true);

        let bytes = value.as_bytes();

        if bytes.len() < MAX_SHORT_STRING {
            self.write_bit(false);
            self.write_u8(bytes.len() as u8);
        } else {
            self.write_bit(true);
            self.write_uint(bytes.len() as u32, 32);
        }

        self.write_bits(bytes, bytes.len() as u32 * 8);
    }

    /// The "a resource, or none" shape used all over the protocol: one bit, then 32 bits.
    pub fn write_optional_u32(&mut self, value: Option<u32>) {
        self.write_bit(value.is_some());

        if let Some(value) = value {
            self.write_uint(value, 32);
        }
    }

    /// Write a game packet id, offset by [`ID_USER_PACKET_ENUM`].
    ///
    /// Anything reaching 255 is escaped: `0xFF` followed by the remainder. 255 is RakNet's
    /// own marker for "the id continues in the next byte".
    pub fn write_packet_id(&mut self, id: u16) {
        let wire = id + ID_USER_PACKET_ENUM;

        if wire >= 255 {
            self.write_u8(0xFF);
            self.write_u8((wire - 255) as u8);
        } else {
            self.write_u8(wire as u8);
        }
    }
}

// --- reading --------------------------------------------------------------------------------

/// The inverse of [`BitWriter`]. Every read is bounds-checked: this parses packets from an
/// untrusted peer, and a panic in a packet handler takes down every connected player.
#[derive(Debug, Clone)]
pub struct BitReader<'a> {
    data: &'a [u8],
    /// Total readable bits — RakNet carries this separately from the byte length.
    bits: usize,
    offset: usize,
}

impl<'a> BitReader<'a> {
    pub fn new(data: &'a [u8], bits: usize) -> Self {
        Self {
            data,
            bits: bits.min(data.len() * 8),
            offset: 0,
        }
    }

    /// Read a whole packet, taking every bit of `data` as readable.
    pub fn from_bytes(data: &'a [u8]) -> Self {
        Self::new(data, data.len() * 8)
    }

    pub fn bits_read(&self) -> usize {
        self.offset
    }

    pub fn bits_remaining(&self) -> usize {
        self.bits - self.offset
    }

    pub fn is_empty(&self) -> bool {
        self.bits_remaining() == 0
    }

    fn require(&self, wanted: usize) -> Result<(), BitError> {
        if self.bits_remaining() < wanted {
            return Err(BitError::OutOfBounds {
                wanted,
                available: self.bits_remaining(),
            });
        }

        Ok(())
    }

    pub fn read_bit(&mut self) -> Result<bool, BitError> {
        self.require(1)?;

        let byte = self.data[self.offset / 8];
        let bit = byte & (0x80 >> (self.offset % 8)) != 0;

        self.offset += 1;

        Ok(bit)
    }

    pub fn read_u8(&mut self) -> Result<u8, BitError> {
        self.read_byte_bits(8)
    }

    /// Read `count <= 8` bits into the top of a byte.
    fn read_byte_bits(&mut self, count: u32) -> Result<u8, BitError> {
        self.require(count as usize)?;

        let mut byte = 0u8;

        for index in 0..count {
            if self.read_bit()? {
                byte |= 0x80 >> index;
            }
        }

        Ok(byte)
    }

    /// The inverse of [`BitWriter::write_uint`].
    pub fn read_uint(&mut self, bits: u32) -> Result<u32, BitError> {
        self.require(bits as usize)?;

        let mut bytes = [0u8; 4];
        let mut remaining = bits;
        let mut index = 0;

        while remaining > 0 {
            let byte = if remaining >= 8 {
                remaining -= 8;
                self.read_byte_bits(8)?
            } else {
                let byte = self.read_byte_bits(remaining)? >> (8 - remaining);
                remaining = 0;
                byte
            };

            if index < bytes.len() {
                bytes[index] = byte;
            }

            index += 1;
        }

        Ok(u32::from_le_bytes(bytes))
    }

    pub fn read_string(&mut self) -> Result<String, BitError> {
        if !self.read_bit()? {
            return Ok(String::new());
        }

        if self.read_bit()? {
            return Err(BitError::LargeStringLength);
        }

        let length = self.read_u8()? as usize;

        // Check before allocating: the length byte is peer-controlled.
        self.require(length * 8)?;

        let mut bytes = Vec::with_capacity(length);

        for _ in 0..length {
            bytes.push(self.read_u8()?);
        }

        String::from_utf8(bytes).map_err(|_| BitError::BadUtf8)
    }

    pub fn read_optional_u32(&mut self) -> Result<Option<u32>, BitError> {
        if self.read_bit()? {
            Ok(Some(self.read_uint(32)?))
        } else {
            Ok(None)
        }
    }

    /// The inverse of [`BitWriter::write_packet_id`].
    pub fn read_packet_id(&mut self) -> Result<u16, BitError> {
        let first = self.read_u8()?;

        let wire = if first == 0xFF {
            255 + u16::from(self.read_u8()?)
        } else {
            u16::from(first)
        };

        Ok(wire.saturating_sub(ID_USER_PACKET_ENUM))
    }
}
