//! A pure-Rust reimplementation of the subset of RakNet's `BitStream` the game uses.
//!
//! Verified byte-for-byte against the real `libRakNet.so` — see `tests/bitstream_golden.rs`
//! and the vectors it reads, which were generated by `tools/bitstream-golden`. Nothing here
//! is inferred from reading the RakNet source; every rule below is a captured measurement.
//!
//! # The rules
//!
//! 1. **Bits fill each byte from the most significant end down.** The first bit written
//!    lands in `0x80`, not `0x01`.
//!
//! 2. **The final partial byte contributes its low bits**, emitted most-significant-first.
//!    RakNet gets there by left-shifting the byte first, which is where "right aligned"
//!    comes from.
//!
//! 3. **There are two different 32-bit writes, and they disagree.** This is the trap.
//!
//!    - [`BitWriter::write_u32`] is RakNet's own `Write<T>`: **big-endian**.
//!      `0x12345678` → `12 34 56 78`. This is what the *client* uses for every 32-bit
//!      field — entity ids, name hashes, list counts.
//!    - [`BitWriter::write_bits_le`] is the C# emulator's
//!      `WriteBits(BitConverter.GetBytes(v), n, true)` idiom: **little-endian**.
//!      `0x12345678` → `78 56 34 12`.
//!
//!    They agree only for widths under 8, where byte order cannot show. So `write_bits_le`
//!    is for narrow fields (a 2-bit gender, a 3-bit response) and `write_u32` for anything
//!    a full word wide.
//!
//!    This was caught by the client, not by the C#. The golden generator originally used
//!    the `WriteBits` idiom for 32-bit fields, so the C# faithfully reproduced the mistake
//!    and every test passed. Decoding a live `SetCharacterCustomisationData` capture settled
//!    it: read big-endian, all six ids resolve to real geodata names (`Human`,
//!    `Human_Skin_Mid1`, `HumanFemaleHairstyle01`, …); read little-endian, none of them do.
//!
//! 4. **A `write_bits_le` width that is not a multiple of 8 is not "the low `n` bits".**
//!    15 bits of `12800` is byte 0 (`0x00`) then the low 7 bits of byte 1 (`0x32`), giving
//!    `00 64` — which does not encode 12800 in any recoverable way. `SkySaga.Game`'s
//!    `TryReadBitsValue` documents the read-side half of this, and the 15-bit pitch fields
//!    in `EntityMoved` / `SetLookAtDirection` are decoded wrongly in the C# because of it.

use thiserror::Error;

/// RakNet's first user-assignable message id. Game packet ids are offsets from here.
pub const ID_USER_PACKET_ENUM: u16 = 134;

/// A string field's length is a single byte unless the `largeLength` bit is set.
const MAX_SHORT_STRING: usize = 255;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum BitError {
    #[error("read past the end: wanted {wanted} bits, {available} remain")]
    OutOfBounds { wanted: usize, available: usize },

    #[error("string field is not valid UTF-8")]
    BadUtf8,

    #[error("large-length strings are not implemented (the game never sends one)")]
    LargeStringLength,
}

// --- writing --------------------------------------------------------------------------------

/// Appends bits most-significant-first, exactly as RakNet does.
#[derive(Debug, Default, Clone)]
pub struct BitWriter {
    data: Vec<u8>,
    bits: usize,
}

impl BitWriter {
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of bits written so far. RakNet sends this, not the byte count.
    pub fn bits_used(&self) -> usize {
        self.bits
    }

    /// The packet, padded to a whole number of bytes.
    pub fn as_bytes(&self) -> &[u8] {
        &self.data
    }

    pub fn into_bytes(self) -> Vec<u8> {
        self.data
    }

    pub fn is_empty(&self) -> bool {
        self.bits == 0
    }

    pub fn write_bit(&mut self, bit: bool) {
        let offset = self.bits % 8;

        if offset == 0 {
            self.data.push(0);
        }

        if bit {
            let last = self.data.len() - 1;

            self.data[last] |= 0x80 >> offset;
        }

        self.bits += 1;
    }

    pub fn write_u8(&mut self, value: u8) {
        self.write_byte_bits(value, 8);
    }

    /// Write the top `count` bits of `value` (`count <= 8`), most-significant-first.
    fn write_byte_bits(&mut self, value: u8, count: u32) {
        for index in 0..count {
            self.write_bit(value & (0x80 >> index) != 0);
        }
    }

    /// A 32-bit value, **big-endian** — RakNet's own `Write<T>`.
    ///
    /// This is what the client uses for every 32-bit field: entity ids, name hashes, list
    /// counts. Verified against a live `SetCharacterCustomisationData` capture, where
    /// big-endian resolves all six ids to real geodata names and little-endian resolves none.
    ///
    /// Do not reach for [`Self::write_bits`] with a width of 32 instead. That is the C#
    /// emulator's `WriteBits(BitConverter.GetBytes(v), 32, true)` idiom, which is
    /// little-endian and produces the byte-reversed value.
    pub fn write_u32(&mut self, value: u32) {
        self.write_bits(&value.to_be_bytes(), 32);
    }

    /// A 16-bit value, big-endian -- RakNet `Write<uint16>`, used for `ChatPort`.
    pub fn write_u16(&mut self, value: u16) {
        self.write_bits(&value.to_be_bytes(), 16);
    }

    /// Write the low `bits` bits of `value` using the C# emulator's
    /// `WriteBits(BitConverter.GetBytes(value), bits, rightAligned: true)` idiom.
    ///
    /// **Little-endian**, so this agrees with [`Self::write_u32`] only for widths under 8,
    /// where byte order cannot show. Use it for narrow fields — a 2-bit gender, a 3-bit
    /// response code — and use `write_u32` for anything 32 bits wide.
    pub fn write_bits_le(&mut self, value: u32, bits: u32) {
        self.write_bits(&value.to_le_bytes(), bits);
    }

    /// The general form: consume `bits` bits from `bytes`, in order.
    ///
    /// Each whole byte contributes all eight of its bits, most-significant-first. A trailing
    /// partial byte contributes its **low** bits, also most-significant-first — RakNet does
    /// this by left-shifting the byte first, which is where "right aligned" comes from.
    pub fn write_bits(&mut self, bytes: &[u8], bits: u32) {
        let mut remaining = bits;
        let mut index = 0;

        while remaining > 0 {
            let byte = bytes.get(index).copied().unwrap_or(0);

            if remaining >= 8 {
                self.write_byte_bits(byte, 8);
                remaining -= 8;
            } else {
                self.write_byte_bits(byte << (8 - remaining), remaining);
                remaining = 0;
            }

            index += 1;
        }
    }

    /// A 64-bit value in the emulator's little-endian `WriteUInt64` form.
    ///
    /// `WriteBits(BitConverter.GetBytes(value), 64, true)` -- the same idiom as
    /// [`Self::write_bits_le`], widened. Not big-endian like [`Self::write_u32`].
    pub fn write_u64_le(&mut self, value: u64) {
        self.write_bits(&value.to_le_bytes(), 64);
    }

    /// Pad with zero bits up to the next byte boundary.
    ///
    /// RakNet does this by advancing its bit counter; the bits it skips are zero because the
    /// buffer is zeroed, so writing zeros explicitly is byte-identical and does not depend on
    /// that.
    pub fn align_to_byte(&mut self) {
        while self.bits % 8 != 0 {
            self.write_bit(false);
        }
    }

    /// `WriteAlignedBytes`: align, then copy the bytes verbatim.
    ///
    /// Used for bulk payloads -- a chunk's voxel arrays -- where the alignment lets RakNet
    /// memcpy instead of shifting every byte.
    pub fn write_aligned_bytes(&mut self, bytes: &[u8]) {
        self.align_to_byte();

        for &byte in bytes {
            self.write_u8(byte);
        }
    }

    /// Append `bits` bits taken from the top of `bytes`, in order.
    ///
    /// The exact inverse of [`BitReader::read_bits_msb`], and *not* the same as
    /// [`Self::write_bits`]: that one takes a trailing partial byte from its **low** bits
    /// (RakNet's "right aligned"), whereas this takes it from the high bits, which is where a
    /// bit-by-bit read leaves it. Use this pair for opaque payloads that must be reproduced
    /// exactly -- an entity's sync data, a chunk's voxels.
    pub fn write_bits_msb(&mut self, bytes: &[u8], bits: usize) {
        for index in 0..bits {
            let byte = bytes.get(index / 8).copied().unwrap_or(0);

            self.write_bit(byte & (0x80 >> (index % 8)) != 0);
        }
    }

    /// A length-optimised unsigned int: one flag bit, then 7 or 32 bits.
    ///
    /// Values below `0x80` take the short form, which is 8 bits in total instead of 33. The
    /// boundary matters: the reader takes its bit count from the flag alone, so writing the
    /// wrong form desynchronises everything after it in the packet rather than just
    /// corrupting this value.
    ///
    /// Both forms are little-endian ([`Self::write_bits_le`]), not the big-endian
    /// [`Self::write_u32`] — see the module docs on the two disagreeing 32-bit writes.
    pub fn write_compressed_u32(&mut self, value: u32) {
        if value < 0x80 {
            self.write_bit(false);
            self.write_bits_le(value, 7);
        } else {
            self.write_bit(true);
            self.write_bits_le(value, 32);
        }
    }

    /// `hasData` bit, `largeLength` bit, an 8-bit length, then the UTF-8 bytes.
    ///
    /// An empty string is a single `0` bit — the client reads that back as empty, so the
    /// length and body are not written at all.
    pub fn write_string(&mut self, value: &str) {
        if value.is_empty() {
            self.write_bit(false);

            return;
        }

        self.write_bit(true);

        let bytes = value.as_bytes();

        if bytes.len() < MAX_SHORT_STRING {
            self.write_bit(false);
            self.write_u8(bytes.len() as u8);
        } else {
            self.write_bit(true);
            self.write_u32(bytes.len() as u32);
        }

        self.write_bits(bytes, bytes.len() as u32 * 8);
    }

    /// The "a resource, or none" shape used all over the protocol: one bit, then 32 bits.
    pub fn write_optional_u32(&mut self, value: Option<u32>) {
        self.write_bit(value.is_some());

        if let Some(value) = value {
            self.write_u32(value);
        }
    }

    /// Write a game packet id, offset by [`ID_USER_PACKET_ENUM`].
    ///
    /// Anything reaching 255 is escaped: `0xFF` followed by the remainder. 255 is RakNet's
    /// own marker for "the id continues in the next byte".
    pub fn write_packet_id(&mut self, id: u16) {
        let wire = id + ID_USER_PACKET_ENUM;

        if wire >= 255 {
            self.write_u8(0xFF);
            self.write_u8((wire - 255) as u8);
        } else {
            self.write_u8(wire as u8);
        }
    }
}

// --- reading --------------------------------------------------------------------------------

/// The inverse of [`BitWriter`]. Every read is bounds-checked: this parses packets from an
/// untrusted peer, and a panic in a packet handler takes down every connected player.
#[derive(Debug, Clone)]
pub struct BitReader<'a> {
    data: &'a [u8],
    /// Total readable bits — RakNet carries this separately from the byte length.
    bits: usize,
    offset: usize,
}

impl<'a> BitReader<'a> {
    pub fn new(data: &'a [u8], bits: usize) -> Self {
        Self {
            data,
            bits: bits.min(data.len() * 8),
            offset: 0,
        }
    }

    /// Read a whole packet, taking every bit of `data` as readable.
    pub fn from_bytes(data: &'a [u8]) -> Self {
        Self::new(data, data.len() * 8)
    }

    pub fn bits_read(&self) -> usize {
        self.offset
    }

    pub fn bits_remaining(&self) -> usize {
        self.bits - self.offset
    }

    pub fn is_empty(&self) -> bool {
        self.bits_remaining() == 0
    }

    fn require(&self, wanted: usize) -> Result<(), BitError> {
        if self.bits_remaining() < wanted {
            return Err(BitError::OutOfBounds {
                wanted,
                available: self.bits_remaining(),
            });
        }

        Ok(())
    }

    pub fn read_bit(&mut self) -> Result<bool, BitError> {
        self.require(1)?;

        let byte = self.data[self.offset / 8];
        let bit = byte & (0x80 >> (self.offset % 8)) != 0;

        self.offset += 1;

        Ok(bit)
    }

    pub fn read_u8(&mut self) -> Result<u8, BitError> {
        self.read_byte_bits(8)
    }

    /// Read `count <= 8` bits into the top of a byte.
    fn read_byte_bits(&mut self, count: u32) -> Result<u8, BitError> {
        self.require(count as usize)?;

        let mut byte = 0u8;

        for index in 0..count {
            if self.read_bit()? {
                byte |= 0x80 >> index;
            }
        }

        Ok(byte)
    }

    /// The inverse of [`BitWriter::write_u32`] -- 32 bits, big-endian.
    pub fn read_u32(&mut self) -> Result<u32, BitError> {
        let mut bytes = [0u8; 4];

        for byte in &mut bytes {
            *byte = self.read_u8()?;
        }

        Ok(u32::from_be_bytes(bytes))
    }

    /// The inverse of [`BitWriter::write_u16`] -- 16 bits, big-endian.
    pub fn read_u16(&mut self) -> Result<u16, BitError> {
        Ok(u16::from_be_bytes([self.read_u8()?, self.read_u8()?]))
    }

    /// The inverse of [`BitWriter::write_bits_le`].
    pub fn read_bits_le(&mut self, bits: u32) -> Result<u32, BitError> {
        self.require(bits as usize)?;

        let mut bytes = [0u8; 4];
        let mut remaining = bits;
        let mut index = 0;

        while remaining > 0 {
            let byte = if remaining >= 8 {
                remaining -= 8;
                self.read_byte_bits(8)?
            } else {
                let byte = self.read_byte_bits(remaining)? >> (8 - remaining);
                remaining = 0;
                byte
            };

            if index < bytes.len() {
                bytes[index] = byte;
            }

            index += 1;
        }

        Ok(u32::from_le_bytes(bytes))
    }

    /// The inverse of [`BitWriter::write_u64_le`].
    pub fn read_u64_le(&mut self) -> Result<u64, BitError> {
        let mut bytes = [0u8; 8];

        for byte in &mut bytes {
            *byte = self.read_u8()?;
        }

        Ok(u64::from_le_bytes(bytes))
    }

    /// Skip to the next byte boundary. The inverse of [`BitWriter::align_to_byte`].
    pub fn align_to_byte(&mut self) -> Result<(), BitError> {
        while self.offset % 8 != 0 {
            self.read_bit()?;
        }

        Ok(())
    }

    /// The inverse of [`BitWriter::write_aligned_bytes`].
    pub fn read_aligned_bytes(&mut self, count: usize) -> Result<Vec<u8>, BitError> {
        self.align_to_byte()?;
        self.require(count * 8)?;

        let mut out = Vec::with_capacity(count.min(1 << 16));

        for _ in 0..count {
            out.push(self.read_u8()?);
        }

        Ok(out)
    }

    /// Read `bits` bits into a byte vector, packed most-significant-first.
    ///
    /// The exact inverse of [`BitWriter::write_bits_msb`]. Used for payloads this crate does
    /// not interpret, so they can be carried and re-emitted unchanged.
    pub fn read_bits_msb(&mut self, bits: usize) -> Result<Vec<u8>, BitError> {
        self.require(bits)?;

        let mut out = vec![0u8; bits.div_ceil(8)];

        for index in 0..bits {
            if self.read_bit()? {
                out[index / 8] |= 0x80 >> (index % 8);
            }
        }

        Ok(out)
    }

    /// Step over `bits` without decoding them.
    ///
    /// For fields a packet carries but the server has no use for. Skipping is not the same as
    /// ignoring: the count has to be exact, or everything after it reads as noise.
    pub fn skip_bits(&mut self, bits: u32) -> Result<(), BitError> {
        let bits = bits as usize;

        self.require(bits)?;
        self.offset += bits;

        Ok(())
    }

    /// The inverse of [`BitWriter::write_compressed_u32`].
    pub fn read_compressed_u32(&mut self) -> Result<u32, BitError> {
        let large = self.read_bit()?;

        self.read_bits_le(if large { 32 } else { 7 })
    }

    pub fn read_string(&mut self) -> Result<String, BitError> {
        if !self.read_bit()? {
            return Ok(String::new());
        }

        if self.read_bit()? {
            return Err(BitError::LargeStringLength);
        }

        let length = self.read_u8()? as usize;

        // Check before allocating: the length byte is peer-controlled.
        self.require(length * 8)?;

        let mut bytes = Vec::with_capacity(length);

        for _ in 0..length {
            bytes.push(self.read_u8()?);
        }

        String::from_utf8(bytes).map_err(|_| BitError::BadUtf8)
    }

    pub fn read_optional_u32(&mut self) -> Result<Option<u32>, BitError> {
        if self.read_bit()? {
            Ok(Some(self.read_u32()?))
        } else {
            Ok(None)
        }
    }

    /// The inverse of [`BitWriter::write_packet_id`].
    pub fn read_packet_id(&mut self) -> Result<u16, BitError> {
        let first = self.read_u8()?;

        let wire = if first == 0xFF {
            255 + u16::from(self.read_u8()?)
        } else {
            u16::from(first)
        };

        Ok(wire.saturating_sub(ID_USER_PACKET_ENUM))
    }
}

/// Width of a ranged field whose declared maximum is `max`.
///
/// The client's `NumBitsRequired` returns the *leading-zero* count, so the width it uses is
/// `32 - that`, which is `32 - leading_zeros(max)`. A field declared with a maximum of 45
/// is therefore 6 bits, and one declared `0x10000` is 17.
///
/// Note this is the width only. Which of [`BitWriter::write_u32`] and
/// [`BitWriter::write_bits_le`] to pair it with is a separate question, and rule 3 above is
/// the one that decides it.
pub const fn ranged_bits(max: u32) -> u32 {
    32 - skysaga_core::bits::num_bits_required(max)
}
