//! Terrain generation, against the chunks the C# server actually sent.
//!
//! This is a stricter check than it looks. Value noise is chaotic: any difference in the
//! integer hash, the shift semantics, the float rounding or the axis order changes most of
//! the 32768 voxels, not a few. Byte equality across all sixteen chunks means the port is
//! exact rather than approximately right.

use skysaga_proto::bitstream::{BitReader, ID_USER_PACKET_ENUM};
use skysaga_proto::packets::ChunkSync;
use skysaga_world::terrain::{blocks, CHUNK_SIZE, VOXELS_PER_CHUNK};
use skysaga_world::TerrainGenerator;

const CAPTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../skysaga-proto/tests/fixtures/handshake.tsv"
);

/// The captured chunks, keyed by coordinates.
fn captured_chunks() -> Vec<ChunkSync> {
    let text = std::fs::read_to_string(CAPTURE).expect("capture");

    text.lines()
        .filter(|line| line.starts_with("server_142_"))
        .map(|line| {
            let fields: Vec<&str> = line.split('\t').collect();
            let bytes: Vec<u8> = (0..fields[2].len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&fields[2][i..i + 2], 16).unwrap())
                .collect();

            let mut reader = BitReader::from_bytes(&bytes);
            let id = reader.read_packet_id().unwrap();

            assert_eq!(id + ID_USER_PACKET_ENUM, 142);

            ChunkSync::decode(&mut reader).expect("ChunkSync decodes")
        })
        .collect()
}

/// Every chunk the C# sent, regenerated byte for byte.
#[test]
fn the_generator_reproduces_every_captured_chunk() {
    let generator = TerrainGenerator::default();

    let captured = captured_chunks();

    assert_eq!(captured.len(), 16, "the home island is 4x4");

    for chunk in &captured {
        let [x, y, z] = chunk.coords;

        let ours = generator
            .chunk(x as usize, y as usize, z as usize)
            .unwrap_or_else(|| panic!("chunk {x},{y},{z} generated as empty"));

        let theirs = chunk.data1.as_ref().expect("voxel data");

        assert_eq!(ours.len(), theirs.len(), "chunk {x},{y},{z} length");

        if &ours != theirs {
            // Report *where* it diverges rather than dumping 32 KB of hex.
            let first = ours
                .iter()
                .zip(theirs)
                .position(|(a, b)| a != b)
                .expect("lengths matched but contents differ");

            let differing = ours.iter().zip(theirs).filter(|(a, b)| a != b).count();

            panic!(
                "chunk {x},{y},{z}: {differing} of {} bytes differ, first at {first} \
                 (ours {}, theirs {})",
                ours.len(),
                ours[first],
                theirs[first],
            );
        }
    }
}

/// The header byte is the compression mode; 0 is raw.
#[test]
fn a_chunk_is_a_mode_byte_followed_by_its_voxels() {
    let chunk = TerrainGenerator::default().chunk(0, 0, 0).expect("solid");

    assert_eq!(chunk.len(), VOXELS_PER_CHUNK + 1);
    assert_eq!(chunk[0], 0, "raw mode");
    assert_eq!(VOXELS_PER_CHUNK, 32 * 32 * 32);
}

/// The generated island is actually an island: solid ground with air above and below.
#[test]
fn the_terrain_is_a_floating_island() {
    let generator = TerrainGenerator::default();
    let chunk = generator.chunk(0, 0, 0).expect("solid");

    let mut air = 0;
    let mut solid = 0;

    for &voxel in &chunk[1..] {
        if voxel == blocks::AIR {
            air += 1;
        } else {
            solid += 1;
        }
    }

    assert!(solid > 0, "there is ground");
    assert!(air > 0, "and sky");

    // Column 0,0: air at the top of the chunk, ground somewhere below.
    let top = 1 + (CHUNK_SIZE - 1) * CHUNK_SIZE * CHUNK_SIZE;

    assert_eq!(chunk[top], blocks::AIR, "the top layer is open sky");
}

/// Surfaces are sand, with dirt then stone below — the layering the material function
/// describes.
#[test]
fn columns_are_layered_sand_then_dirt_then_stone() {
    let generator = TerrainGenerator::default();

    let mut seen_sand = false;
    let mut seen_dirt = false;

    for y in 0..64 {
        match generator.material_at(64, y, 64) {
            blocks::SAND => seen_sand = true,
            blocks::DIRT => seen_dirt = true,
            _ => {}
        }
    }

    assert!(seen_sand, "a sandy surface");
    assert!(seen_dirt, "dirt beneath it");
}

/// The spawn point sits above the surface rather than inside it.
#[test]
fn the_spawn_point_is_in_open_air() {
    let generator = TerrainGenerator::default();
    let (x, y, z) = generator.spawn();

    assert_eq!(generator.material_at(x, y, z), blocks::AIR, "not inside rock");
    assert!(y > 0);
}

/// A different seed gives different terrain — proof the seed is actually used, so the match
/// above is not accidentally seed-independent.
#[test]
fn the_seed_changes_the_terrain() {
    let a = TerrainGenerator::default().chunk(0, 0, 0).unwrap();

    let b = TerrainGenerator {
        seed: 9001,
        ..Default::default()
    }
    .chunk(0, 0, 0)
    .unwrap();

    assert_ne!(a, b);
}
