// Dumps the exact bytes the real RakNet BitStream produces for each primitive and for the
// character-creation packets, so the pure-Rust BitStream in crates/skysaga-proto can be
// tested against them instead of against its author's reading of the RakNet source.
//
// The WriteString / WritePacketId logic below is copied verbatim from
// server/Servers/SkySaga.Game/Extensions/BitStreamExtensions.cs -- this tool deliberately
// does not reference SkySaga.Game, so that the copy stays a readable statement of the format.
//
//   dotnet run -c Release --project tools/bitstream-golden > crates/skysaga-proto/tests/golden/bitstream.txt
//
// Needs libRakNet.so next to the binary; see ../../../scripts/build-raknet.sh.

using System;
using System.Text;

using RakNet;

static void Dump(string label, Action<BitStream> write)
{
    var bitStream = new BitStream();

    write(bitStream);

    var bits = bitStream.GetNumberOfBitsUsed();
    var bytes = bitStream.GetNumberOfBytesUsed();

    // GetData() hands back the whole internal buffer; only the used prefix is meaningful.
    var data = bitStream.GetData()[..(int)bytes];

    Console.WriteLine($"{label}\t{bits}\t{Convert.ToHexString(data).ToLowerInvariant()}");
}

// --- the emulator's own extensions, copied from BitStreamExtensions.cs -------------------

static void WriteString(BitStream bitStream, string? value)
{
    if (string.IsNullOrEmpty(value))
    {
        bitStream.Write0();
        return;
    }

    bitStream.Write1();

    var bytes = Encoding.UTF8.GetBytes(value);
    var length = bytes.Length;

    if (length < 255)
    {
        bitStream.Write0();
        bitStream.Write((byte)length);
    }
    else
    {
        bitStream.Write1();
        bitStream.Write(length);
    }

    bitStream.WriteBits(bytes, (uint)length * 8u, true);
}

static void WritePacketId(BitStream bitStream, int packetId)
{
    var id = (byte)packetId;
    var part = (byte)(id - (byte.MaxValue + 1 - (byte)DefaultMessageIDTypes.ID_USER_PACKET_ENUM));

    if (id + (byte)DefaultMessageIDTypes.ID_USER_PACKET_ENUM >= byte.MaxValue)
    {
        bitStream.Write(byte.MaxValue);
        part++;
    }

    bitStream.Write(part);
}

static void WriteOptionalUInt(BitStream bitStream, uint? value)
{
    bitStream.Write(value.HasValue);

    if (value.HasValue)
        bitStream.Write((int)value.Value);
}

// A list with a zero-bit count field: the count is implicit, one escape bit says whether it
// is the default, and a full 32-bit count follows only when it is not.
// See documentations/character-and-appearance.md section 3.
static void WriteCountOptimisedList(BitStream bitStream, int count, int defaultCount, Action write)
{
    if (count == defaultCount)
    {
        bitStream.Write0();
    }
    else
    {
        bitStream.Write1();
        bitStream.Write(count);
    }

    write();
}

Console.WriteLine("# label\tbits\thex   -- generated by tools/bitstream-golden");
Console.WriteLine($"# pointer size {IntPtr.Size}, RakNet via libRakNet.so");

// --- primitives --------------------------------------------------------------------------

Dump("write0", bs => bs.Write0());
Dump("write1", bs => bs.Write1());
Dump("write0_write1", bs => { bs.Write0(); bs.Write1(); });
Dump("write_bool_true", bs => bs.Write(true));
Dump("write_bool_false", bs => bs.Write(false));
Dump("write_u8_0x12", bs => bs.Write((byte)0x12));
Dump("write_u8_0xff", bs => bs.Write((byte)0xff));
Dump("write_u8_twice", bs => { bs.Write((byte)0xab); bs.Write((byte)0xcd); });

// One bit of misalignment before a byte -- this is where bit order actually shows.
Dump("bit_then_u8", bs => { bs.Write1(); bs.Write((byte)0x12); });
Dump("three_bits_then_u8", bs => { bs.Write1(); bs.Write0(); bs.Write1(); bs.Write((byte)0xff); });

// --- WriteBits at the widths the character packets use -----------------------------------

foreach (var (width, value) in new[]
{
    (2u, 1), (2u, 2), (3u, 0), (3u, 2), (3u, 4), (4u, 11), (7u, 100),
    (15u, 12800), (26u, 4), (32u, 7), (32u, 0x12345678),
})
{
    Dump($"write_bits_{width}_{value}", bs => bs.WriteBits(BitConverter.GetBytes(value), width, true));
}

// Misaligned, so the shifting path is exercised rather than the fast path.
Dump("bit_then_write_bits_3_5", bs => { bs.Write1(); bs.WriteBits(BitConverter.GetBytes(5), 3, true); });
Dump("bit_then_write_bits_32_7", bs => { bs.Write1(); bs.WriteBits(BitConverter.GetBytes(7), 32, true); });

// RakNet's own Write<T>, which is NOT the same as WriteBits(GetBytes(v), 32, true): it
// byte-swaps to network order. The client uses this form for every 32-bit field, verified by
// decoding a live SetCharacterCustomisationData capture -- big-endian resolves all six ids to
// real geodata names, little-endian resolves none. The emulator's WriteBits idiom is the
// odd one out and is only correct for widths under 8, where byte order cannot show.
Dump("write_u32_native_7", bs => bs.Write(7));
Dump("write_u32_native_12", bs => bs.Write(12));
Dump("write_u32_native_0x12345678", bs => bs.Write(0x12345678));
Dump("write_u32_native_crc_human", bs => bs.Write(unchecked((int)1319509738u)));
Dump("bit_then_write_u32_native_7", bs => { bs.Write1(); bs.Write(7); });

// --- strings ------------------------------------------------------------------------------

Dump("string_empty", bs => WriteString(bs, ""));
Dump("string_null", bs => WriteString(bs, null));
Dump("string_A", bs => WriteString(bs, "A"));
Dump("string_Alice", bs => WriteString(bs, "Alice"));
Dump("string_Sky_Island", bs => WriteString(bs, "Sky_Island"));
Dump("string_uuid", bs => WriteString(bs, "8438a953-1a08-4959-9717-dff15d6e3574"));
Dump("bit_then_string_Alice", bs => { bs.Write1(); WriteString(bs, "Alice"); });

// --- packet ids ---------------------------------------------------------------------------

foreach (var id in new[] { 37, 108, 109, 110, 120, 121, 150 })
    Dump($"packet_id_{id}", bs => WritePacketId(bs, id));

// --- optional uint32 ----------------------------------------------------------------------

Dump("optional_none", bs => WriteOptionalUInt(bs, null));
Dump("optional_some_0", bs => WriteOptionalUInt(bs, 0));
Dump("optional_some_crc_cat", bs => WriteOptionalUInt(bs, 253473828));

// --- whole packets ------------------------------------------------------------------------

// SaveCharacterName -- 108, one string. (Client -> server, so this is the read-side oracle.)
Dump("packet_save_character_name_Alice", bs =>
{
    WritePacketId(bs, 108);
    WriteString(bs, "Alice");
});

// CreateHomeworld -- 110, two strings.
Dump("packet_create_homeworld", bs =>
{
    WritePacketId(bs, 110);
    WriteString(bs, "Sky_Island");
    WriteString(bs, "8438a953-1a08-4959-9717-dff15d6e3574");
});

// CharcterCreationResponse -- 109, a 3-bit response. This is the one the server sends.
foreach (var response in new[] { 0, 1, 2, 3 })
{
    Dump($"packet_character_creation_response_{response}", bs =>
    {
        WritePacketId(bs, 109);
        bs.WriteBits(BitConverter.GetBytes(response), 3, true);
    });
}

// SetCharacterCustomisationData -- 37: entityID then the struct.
//   gender      2 bits
//   tribe       optional uint32
//   materials   count-optimised list, default 3, of optional uint32
//   attachments count-optimised list, default 1, of (optional uint32, optional uint32)
Dump("packet_set_character_customisation", bs =>
{
    WritePacketId(bs, 37);
    bs.Write(4242);                                              // entityID

    bs.WriteBits(BitConverter.GetBytes(1), 2, true);              // gender = Female
    WriteOptionalUInt(bs, 1319509738);                            // tribe = Human

    WriteCountOptimisedList(bs, 3, 3, () =>
    {
        WriteOptionalUInt(bs, 111);                               // skin
        WriteOptionalUInt(bs, 222);                               // eyes
        WriteOptionalUInt(bs, 333);                               // clothing
    });

    WriteCountOptimisedList(bs, 1, 1, () =>
    {
        WriteOptionalUInt(bs, 2632453954);                        // hairstyle
        WriteOptionalUInt(bs, 444);                               // hair colour
    });
});

// The same struct with everything absent, so the optional-none path is covered end to end.
Dump("packet_set_character_customisation_empty", bs =>
{
    WritePacketId(bs, 37);
    bs.Write(0);                                                 // entityID

    bs.WriteBits(BitConverter.GetBytes(0), 2, true);
    WriteOptionalUInt(bs, null);

    WriteCountOptimisedList(bs, 3, 3, () =>
    {
        WriteOptionalUInt(bs, null);
        WriteOptionalUInt(bs, null);
        WriteOptionalUInt(bs, null);
    });

    WriteCountOptimisedList(bs, 1, 1, () =>
    {
        WriteOptionalUInt(bs, null);
        WriteOptionalUInt(bs, null);
    });
});

// A non-default count, exercising the escape path the creator never uses.
Dump("packet_customisation_two_attachments", bs =>
{
    bs.WriteBits(BitConverter.GetBytes(0), 2, true);
    WriteOptionalUInt(bs, null);

    WriteCountOptimisedList(bs, 3, 3, () =>
    {
        WriteOptionalUInt(bs, null);
        WriteOptionalUInt(bs, null);
        WriteOptionalUInt(bs, null);
    });

    WriteCountOptimisedList(bs, 2, 1, () =>
    {
        WriteOptionalUInt(bs, 1);
        WriteOptionalUInt(bs, 2);
        WriteOptionalUInt(bs, 3);
        WriteOptionalUInt(bs, 4);
    });
});

return 0;
